version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: hanna369/docker-demo
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output:/usr/share/udemy/allure-results
  flight-module:
    image: hanna369/docker-demo
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=flight-module.xml
  allure:
      image: "frankescobar/allure-docker-service"
      environment:
        CHECK_RESULTS_EVERY_SECONDS: 1
        KEEP_HISTORY: 1
      ports:
        - "5050:5050"
      volumes:
        - /home/qa/jenkins/workspace/Docker_Demo/target/allure-results:/app/allure-results
        - /home/qa/jenkins/workspace/Docker_Demo/target/allure-report:/app/default-reports
