version: "3"
services:
  hub:
    image: selenium/hub:3.14
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: hanna369/docker-demo
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./target/allure-results:/usr/share/udemy/target/allure-results
  flight-module:
    image: hanna369/docker-demo
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=flight-module.xml
    volumes:
      - ./target/allure-results:/usr/share/udemy/target/allure-results